// Code Generated by Sidekick is for learning and experimentation purposes only.

// ==============================
// INITIALIZE AOS ANIMATIONS
// ==============================

AOS.init({
  duration: 1000,
  once: true,
  offset: 100
});

// ==============================
// EMAIL & WHATSAPP CONFIGURATION
// ==============================

// Initialize EmailJS with your Public Key
(function() {
  emailjs.init("YOUR_PUBLIC_KEY"); // Replace with your EmailJS Public Key
})();

// Your contact details
const OWNER_EMAIL = "riteshku999@gmail.com";
const OWNER_WHATSAPP = "918093172004"; // Format: country code + number (no + or spaces)

// EmailJS Configuration
const EMAILJS_SERVICE_ID = "YOUR_SERVICE_ID"; // Replace with your Service ID
const EMAILJS_TEMPLATE_ID = "YOUR_TEMPLATE_ID"; // Replace with your Template ID

// ==============================
// NAVIGATION BAR
// ==============================

const navbar = document.getElementById('navbar');
const navLinks = document.querySelectorAll('.nav-link');
const mobileMenuToggle = document.getElementById('mobileMenuToggle');
const navMenu = document.getElementById('navMenu');

// Navbar scroll effect
window.addEventListener('scroll', () => {
  if (window.scrollY > 50) {
    navbar.classList.add('scrolled');
  } else {
    navbar.classList.remove('scrolled');
  }
});

// Smooth scrolling for navigation links
navLinks.forEach(link => {
  link.addEventListener('click', function(e) {
    e.preventDefault();
    
    // Remove active class from all links
    navLinks.forEach(l => l.classList.remove('active'));
    
    // Add active class to clicked link
    this.classList.add('active');
    
    // Get target section
    const targetId = this.getAttribute('href');
    const targetSection = document.querySelector(targetId);
    
    // Close mobile menu if open
    navMenu.classList.remove('active');
    
    // Scroll to target section
    if (targetSection) {
      const offsetTop = targetSection.offsetTop - 70;
      window.scrollTo({
        top: offsetTop,
        behavior: 'smooth'
      });
    }
  });
});

// Mobile menu toggle
if (mobileMenuToggle) {
  mobileMenuToggle.addEventListener('click', () => {
    navMenu.classList.toggle('active');
  });
}

// Close mobile menu when clicking outside
document.addEventListener('click', (e) => {
  if (!navbar.contains(e.target)) {
    navMenu.classList.remove('active');
  }
});

// Update active nav link on scroll
const sections = document.querySelectorAll('section');

window.addEventListener('scroll', () => {
  let current = '';
  
  sections.forEach(section => {
    const sectionTop = section.offsetTop - 100;
    const sectionHeight = section.clientHeight;
    
    if (window.scrollY >= sectionTop && window.scrollY < sectionTop + sectionHeight) {
      current = section.getAttribute('id');
    }
  });
  
  navLinks.forEach(link => {
    link.classList.remove('active');
    if (link.getAttribute('href') === `#${current}`) {
      link.classList.add('active');
    }
  });
});

// ==============================
// HOT DEALS SECTION - FILTERING & SORTING
// ==============================

document.addEventListener('DOMContentLoaded', function() {
  
  // Select all required elements
  const categoryBtns = document.querySelectorAll('.category-btn');
  const filterBtns = document.querySelectorAll('.filter-btn');
  const sortSelect = document.getElementById('sortDeals');
  const dealCards = document.querySelectorAll('.deal-card');
  const loadMoreBtn = document.getElementById('loadMoreBtn');
  const dealsGrid = document.querySelector('.deals-grid');

  // Check if elements exist (debugging)
  console.log('Category Buttons:', categoryBtns.length);
  console.log('Filter Buttons:', filterBtns.length);
  console.log('Sort Dropdown:', sortSelect ? 'Found' : 'NOT FOUND');
  console.log('Deal Cards:', dealCards.length);
  console.log('Load More Button:', loadMoreBtn ? 'Found' : 'NOT FOUND');
  console.log('Deals Grid:', dealsGrid ? 'Found' : 'NOT FOUND');

  // Configuration
  let currentCategory = 'residential';
  let currentPriceFilter = 'all';
  let currentSort = 'featured';
  let visibleCount = 6; // Show 6 deals initially

  // Store all deals data
  let allDeals = [];
  
  // Extract deal data from HTML cards
  dealCards.forEach((card, index) => {
    const deal = {
      element: card,
      category: card.dataset.category || 'residential',
      price: parseInt(card.dataset.price) || 0,
      location: card.dataset.location || '',
      index: index
    };
    allDeals.push(deal);
  });

  console.log('Total Deals Loaded:', allDeals.length);

  // ==============================
  // CATEGORY FILTER (Residential/Commercial)
  // ==============================
  
  if (categoryBtns.length > 0) {
    categoryBtns.forEach(btn => {
      btn.addEventListener('click', function() {
        // Remove active class from all buttons
        categoryBtns.forEach(b => b.classList.remove('active'));
        
        // Add active class to clicked button
        this.classList.add('active');
        
        // Update current category
        currentCategory = this.dataset.category;
        console.log('Category changed to:', currentCategory);
        
        // Reset visible count
        visibleCount = 6;
        
        // Apply filters
        applyFilters();
      });
    });
  }

  // ==============================
  // PRICE FILTER
  // ==============================
  
  if (filterBtns.length > 0) {
    filterBtns.forEach(btn => {
      btn.addEventListener('click', function() {
        // Remove active class from all buttons
        filterBtns.forEach(b => b.classList.remove('active'));
        
        // Add active class to clicked button
        this.classList.add('active');
        
        // Update current price filter
        currentPriceFilter = this.dataset.filter;
        console.log('Price filter changed to:', currentPriceFilter);
        
        // Reset visible count
        visibleCount = 6;
        
        // Apply filters
        applyFilters();
      });
    });
  }

  // ==============================
  // SORT DROPDOWN
  // ==============================
  
  if (sortSelect) {
    sortSelect.addEventListener('change', function() {
      currentSort = this.value;
      console.log('Sort changed to:', currentSort);
      
      // Apply filters
      applyFilters();
    });
  }

  // ==============================
  // LOAD MORE BUTTON
  // ==============================
  
  if (loadMoreBtn) {
    loadMoreBtn.addEventListener('click', function() {
      console.log('Load More clicked');
      visibleCount += 6; // Show 6 more deals
      applyFilters();
    });
  }

  // ==============================
  // MAIN FILTER FUNCTION
  // ==============================
  
  function applyFilters() {
    console.log('Applying filters:', { currentCategory, currentPriceFilter, currentSort });
    
    // Step 1: Filter by category
    let filteredDeals = allDeals.filter(deal => {
      return deal.category === currentCategory;
    });
    
    console.log('After category filter:', filteredDeals.length);

    // Step 2: Filter by price range
    if (currentPriceFilter !== 'all') {
      filteredDeals = filteredDeals.filter(deal => {
        const price = deal.price;
        
        switch(currentPriceFilter) {
          case 'under-50':
            return price < 5000000; // Under 50 lakhs
          case '50-100':
            return price >= 5000000 && price < 10000000; // 50L - 1Cr
          case '1-2':
            return price >= 10000000 && price < 20000000; // 1-2 Cr
          case 'above-2':
            return price >= 20000000; // Above 2 Cr
          default:
            return true;
        }
      });
    }
    
    console.log('After price filter:', filteredDeals.length);

    // Step 3: Sort deals
    filteredDeals.sort((a, b) => {
      switch(currentSort) {
        case 'price-low':
          return a.price - b.price;
        case 'price-high':
          return b.price - a.price;
        case 'location':
          return a.location.localeCompare(b.location);
        default: // featured
          return a.index - b.index;
      }
    });

    // Step 4: Hide all deals first
    allDeals.forEach(deal => {
      deal.element.style.display = 'none';
    });

    // Step 5: Show filtered deals (up to visibleCount)
    filteredDeals.forEach((deal, index) => {
      if (index < visibleCount) {
        deal.element.style.display = 'block';
      }
    });

    // Step 6: Update Load More button
    if (loadMoreBtn) {
      const remaining = filteredDeals.length - visibleCount;
      
      if (remaining > 0) {
        loadMoreBtn.style.display = 'block';
        loadMoreBtn.textContent = `Load More (${remaining} remaining)`;
      } else {
        loadMoreBtn.style.display = 'none';
      }
    }

    // Step 7: Show message if no deals found
    if (filteredDeals.length === 0) {
      console.log('No deals match the filters');
      // You can add a "No deals found" message here if needed
    }

    console.log('Showing', Math.min(visibleCount, filteredDeals.length), 'of', filteredDeals.length, 'deals');
  }

  // ==============================
  // INITIAL LOAD
  // ==============================
  
  // Apply filters on page load to show initial 6 deals
  applyFilters();

  console.log('Hot Deals functionality initialized successfully!');
});

// ==============================
// CONTACT FORM HANDLING
// ==============================

const contactForm = document.getElementById('contactForm');
const successMessage = document.getElementById('successMessage');

if (contactForm) {
  
  // Form validation
  function validateForm(formData) {
    let isValid = true;
    const errors = {};

    // Name validation
    const fullName = formData.get('fullName').trim();
    if (fullName.length < 2) {
      errors.fullName = 'Please enter a valid name';
      isValid = false;
    }

    // Email validation
    const email = formData.get('email').trim();
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      errors.email = 'Please enter a valid email address';
      isValid = false;
    }

    // Phone validation (Indian format)
    const phone = formData.get('phone').trim();
    const phoneRegex = /^[\+]?[0-9]{10,15}$/;
    if (!phoneRegex.test(phone.replace(/[\s\-\(\)]/g, ''))) {
      errors.phone = 'Please enter a valid phone number';
      isValid = false;
    }

    // Property interest validation
    const propertyInterest = formData.get('propertyInterest');
    if (!propertyInterest) {
      errors.propertyInterest = 'Please select your area of interest';
      isValid = false;
    }

    // Message validation
    const message = formData.get('message').trim();
    if (message.length < 10) {
      errors.message = 'Please enter a message (at least 10 characters)';
      isValid = false;
    }

    return { isValid, errors };
  }

  // Display errors
  function displayErrors(errors) {
    // Clear previous errors
    document.querySelectorAll('.form-group').forEach(group => {
      group.classList.remove('error');
      const errorMsg = group.querySelector('.error-message');
      if (errorMsg) errorMsg.textContent = '';
    });

    // Display new errors
    Object.keys(errors).forEach(fieldName => {
      const input = document.getElementById(fieldName);
      if (input) {
        const formGroup = input.closest('.form-group');
        formGroup.classList.add('error');
        const errorMsg = formGroup.querySelector('.error-message');
        if (errorMsg) errorMsg.textContent = errors[fieldName];
      }
    });
  }

  // Send to Email via EmailJS
  async function sendToEmail(formData) {
    const templateParams = {
      from_name: formData.get('fullName'),
      from_email: formData.get('email'),
      from_phone: formData.get('phone'),
      property_interest: formData.get('propertyInterest'),
      budget: formData.get('budget') || 'Not specified',
      message: formData.get('message'),
      submission_date: new Date().toLocaleString('en-IN', { 
        timeZone: 'Asia/Kolkata',
        dateStyle: 'full',
        timeStyle: 'short'
      })
    };

    try {
      const response = await emailjs.send(
        EMAILJS_SERVICE_ID,
        EMAILJS_TEMPLATE_ID,
        templateParams
      );
      console.log('Email sent successfully!', response.status, response.text);
      return true;
    } catch (error) {
      console.error('Email sending failed:', error);
      return false;
    }
  }

  // Send to WhatsApp
  function sendToWhatsApp(formData) {
    const name = formData.get('fullName');
    const email = formData.get('email');
    const phone = formData.get('phone');
    const interest = formData.get('propertyInterest');
    const budget = formData.get('budget') || 'Not specified';
    const message = formData.get('message');

    // Format WhatsApp message
    const whatsappMessage = `*🏠 NEW PROPERTY ENQUIRY - Civium Estate*

*Name:* ${name}
*Email:* ${email}
*Phone:* ${phone}
*Interested In:* ${interest}
*Budget:* ${budget}

*Message:*
${message}

---
_Submitted on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}_`;

    // Encode message for URL
    const encodedMessage = encodeURIComponent(whatsappMessage);
    
    // Open WhatsApp with pre-filled message
    const whatsappURL = `https://wa.me/${OWNER_WHATSAPP}?text=${encodedMessage}`;
    
    // Open in new window (will work on both desktop and mobile)
    window.open(whatsappURL, '_blank');
    
    return true;
  }

  // Handle form submission
  contactForm.addEventListener('submit', async function(e) {
    e.preventDefault();

    const formData = new FormData(contactForm);
    const validation = validateForm(formData);

    if (!validation.isValid) {
      displayErrors(validation.errors);
      return;
    }

    // Clear errors if validation passed
    displayErrors({});

    // Show loading state
    const submitBtn = contactForm.querySelector('.submit-btn');
    const btnText = submitBtn.querySelector('.btn-text');
    const btnLoader = submitBtn.querySelector('.btn-loader');
    
    submitBtn.disabled = true;
    btnText.style.display = 'none';
    btnLoader.style.display = 'inline-block';

    try {
      // Send to Email
      const emailSent = await sendToEmail(formData);
      
      if (emailSent) {
        // Send to WhatsApp (opens WhatsApp)
        sendToWhatsApp(formData);
        
        // Show success message
        contactForm.style.display = 'none';
        successMessage.style.display = 'block';

        // Reset form
        contactForm.reset();

        // Reset form state after 5 seconds
        setTimeout(() => {
          successMessage.style.display = 'none';
          contactForm.style.display = 'flex';
          submitBtn.disabled = false;
          btnText.style.display = 'inline-block';
          btnLoader.style.display = 'none';
        }, 5000);
        
      } else {
        throw new Error('Email sending failed');
      }

    } catch (error) {
      console.error('Form submission error:', error);
      alert('⚠️ There was an issue sending your enquiry. Please contact us directly at:\n\nEmail: riteshku999@gmail.com\nWhatsApp: +91-8093172004');
      
      submitBtn.disabled = false;
      btnText.style.display = 'inline-block';
      btnLoader.style.display = 'none';
    }
  });

  // Real-time validation on blur
  contactForm.querySelectorAll('input, select, textarea').forEach(field => {
    field.addEventListener('blur', function() {
      const formData = new FormData(contactForm);
      const validation = validateForm(formData);
      
      if (validation.errors[this.id]) {
        const formGroup = this.closest('.form-group');
        formGroup.classList.add('error');
        const errorMsg = formGroup.querySelector('.error-message');
        if (errorMsg) errorMsg.textContent = validation.errors[this.id];
      } else {
        const formGroup = this.closest('.form-group');
        formGroup.classList.remove('error');
        const errorMsg = formGroup.querySelector('.error-message');
        if (errorMsg) errorMsg.textContent = '';
      }
    });
  });
}

// ==============================
// CONSOLE LOG
// ==============================

console.log('Civium Estate website loaded successfully! 🏛️');
console.log('All interactive features are ready.');
